name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android NDK >=23
  # You may pin to the exact commit or the version.
  # uses: anoop-b/setup-ndk@6f0ee78e62451cfec5f1698acb00b58d00a5d7b6
      uses: anoop-b/setup-ndk@V1.3.0
      with:
    # Exact version to use
        ndk-version: "25.2.9519653"
    # Add installation directory to the PATH
        add-to-path: true # optional, default is true
    # Use the local job cache on top of the runner tool cache
        local-cache: true # optional, default is false
    

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
